services:
  - type: web
    name: expense-tracker-frontend
    env: node
    region: oregon
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l ${PORT:-10000}
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://expense-tracker-nxc0.onrender.com/api
